import {
  MenuTheme,
  TemplateKey,
  SERIF_STACK,
  SANS_STACK,
  ROUNDED_STACK,
} from './types';

/**
 * 6 layout archetypes × 4 curated themes = 24 presets.
 * Every theme was checked for contrast (body text ≥ ~7:1 on bg,
 * muted ≥ ~4.5:1) in both light and dark sets.
 */

export interface ArchetypeMeta {
  key: TemplateKey;
  name: string;
  tagline: string;
  themes: MenuTheme[];
}

const elegant: MenuTheme[] = [
  {
    key: 'porcelain',
    name: 'Porcelain',
    mode: 'light',
    bg: '#FDFCFA',
    surface: '#FFFFFF',
    text: '#211E19',
    muted: '#6E675C',
    accent: '#A8863C',
    border: '#E5DFD2',
    headingFont: SERIF_STACK,
    bodyFont: SERIF_STACK,
    radius: '2px',
  },
  {
    key: 'champagne',
    name: 'Champagne',
    mode: 'light',
    bg: '#F8F2E7',
    surface: '#FDFAF3',
    text: '#3B2F1E',
    muted: '#7C6D55',
    accent: '#8C6A3F',
    border: '#E4D8C2',
    headingFont: SERIF_STACK,
    bodyFont: SERIF_STACK,
    radius: '2px',
  },
  {
    key: 'ivy',
    name: 'Ivy',
    mode: 'light',
    bg: '#F5F7F2',
    surface: '#FDFEFB',
    text: '#1F2A20',
    muted: '#5C6B5E',
    accent: '#3E5C41',
    border: '#DCE3D8',
    headingFont: SERIF_STACK,
    bodyFont: SERIF_STACK,
    radius: '2px',
  },
  {
    key: 'slate-rose',
    name: 'Slate Rose',
    mode: 'light',
    bg: '#F8F5F6',
    surface: '#FFFFFF',
    text: '#2B2528',
    muted: '#6F6368',
    accent: '#A5586C',
    border: '#E7DEE1',
    headingFont: SERIF_STACK,
    bodyFont: SERIF_STACK,
    radius: '2px',
  },
];

const minimal: MenuTheme[] = [
  {
    key: 'cloud',
    name: 'Cloud',
    mode: 'light',
    bg: '#F5F6F8',
    surface: '#FFFFFF',
    text: '#14181F',
    muted: '#5A6472',
    accent: '#2563EB',
    border: '#E4E7EC',
    headingFont: SANS_STACK,
    bodyFont: SANS_STACK,
    radius: '16px',
  },
  {
    key: 'matcha',
    name: 'Matcha',
    mode: 'light',
    bg: '#F2F6EF',
    surface: '#FFFFFF',
    text: '#1B241A',
    muted: '#59685A',
    accent: '#4D7C4A',
    border: '#DFE8DB',
    headingFont: SANS_STACK,
    bodyFont: SANS_STACK,
    radius: '16px',
  },
  {
    key: 'peach-cream',
    name: 'Peach Cream',
    mode: 'light',
    bg: '#FBF4EE',
    surface: '#FFFFFF',
    text: '#2B211B',
    muted: '#77655A',
    accent: '#C2603E',
    border: '#EFE1D6',
    headingFont: SANS_STACK,
    bodyFont: SANS_STACK,
    radius: '16px',
  },
  {
    key: 'graphite',
    name: 'Graphite',
    mode: 'dark',
    bg: '#151619',
    surface: '#1F2126',
    text: '#EDEEF0',
    muted: '#9AA1AB',
    accent: '#8AB4F8',
    border: '#2C2F36',
    headingFont: SANS_STACK,
    bodyFont: SANS_STACK,
    radius: '16px',
  },
];

const noir: MenuTheme[] = [
  {
    key: 'midnight-gold',
    name: 'Midnight Gold',
    mode: 'dark',
    bg: '#0E0E10',
    surface: '#17171B',
    text: '#EDE8DD',
    muted: '#9C968A',
    accent: '#C9A227',
    border: '#2A2A2F',
    headingFont: SERIF_STACK,
    bodyFont: SANS_STACK,
    radius: '6px',
  },
  {
    key: 'velvet',
    name: 'Velvet',
    mode: 'dark',
    bg: '#170B12',
    surface: '#22121C',
    text: '#F2E6EC',
    muted: '#A8929E',
    accent: '#D0708F',
    border: '#3A2231',
    headingFont: SERIF_STACK,
    bodyFont: SANS_STACK,
    radius: '6px',
  },
  {
    key: 'smoke',
    name: 'Smoke',
    mode: 'dark',
    bg: '#111316',
    surface: '#1A1D21',
    text: '#E4E7EA',
    muted: '#8F98A1',
    accent: '#B9C4CC',
    border: '#2B3036',
    headingFont: SERIF_STACK,
    bodyFont: SANS_STACK,
    radius: '6px',
  },
  {
    key: 'neon',
    name: 'Neon',
    mode: 'dark',
    bg: '#0A0B10',
    surface: '#14161F',
    text: '#E8EAF6',
    muted: '#8B90A8',
    accent: '#22D3EE',
    border: '#252838',
    headingFont: SANS_STACK,
    bodyFont: SANS_STACK,
    radius: '6px',
  },
];

const gallery: MenuTheme[] = [
  {
    key: 'street',
    name: 'Street',
    mode: 'light',
    bg: '#FAFAF8',
    surface: '#FFFFFF',
    text: '#191817',
    muted: '#6A6661',
    accent: '#E11D48',
    border: '#E9E6E1',
    headingFont: SANS_STACK,
    bodyFont: SANS_STACK,
    radius: '18px',
  },
  {
    key: 'citrus',
    name: 'Citrus',
    mode: 'light',
    bg: '#FFFBF0',
    surface: '#FFFFFF',
    text: '#241E12',
    muted: '#75695A',
    accent: '#D97706',
    border: '#F0E7D2',
    headingFont: SANS_STACK,
    bodyFont: SANS_STACK,
    radius: '18px',
  },
  {
    key: 'charcoal-grill',
    name: 'Charcoal Grill',
    mode: 'dark',
    bg: '#151210',
    surface: '#1F1B18',
    text: '#F0EBE5',
    muted: '#A2988D',
    accent: '#F97316',
    border: '#312A24',
    headingFont: SANS_STACK,
    bodyFont: SANS_STACK,
    radius: '18px',
  },
  {
    key: 'ocean',
    name: 'Ocean',
    mode: 'light',
    bg: '#F0F6F8',
    surface: '#FFFFFF',
    text: '#132126',
    muted: '#54696F',
    accent: '#0E7490',
    border: '#DBE8EC',
    headingFont: SANS_STACK,
    bodyFont: SANS_STACK,
    radius: '18px',
  },
];

const bistro: MenuTheme[] = [
  {
    key: 'butcher-paper',
    name: 'Butcher Paper',
    mode: 'light',
    bg: '#F4EADA',
    surface: '#FBF4E8',
    text: '#4A3623',
    muted: '#84705A',
    accent: '#B0502D',
    border: '#E0D2BB',
    headingFont: ROUNDED_STACK,
    bodyFont: SANS_STACK,
    radius: '10px',
  },
  {
    key: 'chalkboard',
    name: 'Chalkboard',
    mode: 'dark',
    bg: '#252E29',
    surface: '#2D3832',
    text: '#F2F0E4',
    muted: '#AEB5A6',
    accent: '#E8C547',
    border: '#3D4A42',
    headingFont: ROUNDED_STACK,
    bodyFont: SANS_STACK,
    radius: '10px',
  },
  {
    key: 'olive-grove',
    name: 'Olive Grove',
    mode: 'light',
    bg: '#F4F2E7',
    surface: '#FBFAF2',
    text: '#31351F',
    muted: '#6E7358',
    accent: '#6B7A3A',
    border: '#E0DECB',
    headingFont: ROUNDED_STACK,
    bodyFont: SANS_STACK,
    radius: '10px',
  },
  {
    key: 'tomato',
    name: 'Tomato',
    mode: 'light',
    bg: '#FDF3EC',
    surface: '#FFFAF6',
    text: '#3A2019',
    muted: '#7E6157',
    accent: '#C63D2F',
    border: '#F0DDD2',
    headingFont: ROUNDED_STACK,
    bodyFont: SANS_STACK,
    radius: '10px',
  },
];

const grand: MenuTheme[] = [
  {
    key: 'royal-navy',
    name: 'Royal Navy',
    mode: 'light',
    bg: '#F6F7F9',
    surface: '#FFFFFF',
    text: '#1B2A4A',
    muted: '#5A6880',
    accent: '#B08D3E',
    border: '#DDE1E9',
    headingFont: SERIF_STACK,
    bodyFont: SERIF_STACK,
    radius: '4px',
  },
  {
    key: 'burgundy',
    name: 'Burgundy',
    mode: 'light',
    bg: '#FBF7F4',
    surface: '#FFFFFF',
    text: '#46212A',
    muted: '#87656E',
    accent: '#7B2D3B',
    border: '#EBDFD9',
    headingFont: SERIF_STACK,
    bodyFont: SERIF_STACK,
    radius: '4px',
  },
  {
    key: 'emerald-estate',
    name: 'Emerald Estate',
    mode: 'light',
    bg: '#F4F7F5',
    surface: '#FFFFFF',
    text: '#14352B',
    muted: '#587268',
    accent: '#1E6B54',
    border: '#DCE5DF',
    headingFont: SERIF_STACK,
    bodyFont: SERIF_STACK,
    radius: '4px',
  },
  {
    key: 'onyx',
    name: 'Onyx',
    mode: 'dark',
    bg: '#121316',
    surface: '#1B1D21',
    text: '#E9E7E2',
    muted: '#9B9890',
    accent: '#B08D3E',
    border: '#2C2F35',
    headingFont: SERIF_STACK,
    bodyFont: SERIF_STACK,
    radius: '4px',
  },
];

export const ARCHETYPES: ArchetypeMeta[] = [
  {
    key: 'elegant',
    name: 'Elegant',
    tagline: 'Fine dining — serif, whitespace, hairline rules',
    themes: elegant,
  },
  {
    key: 'minimal',
    name: 'Minimal',
    tagline: 'Café & brunch — clean airy cards',
    themes: minimal,
  },
  {
    key: 'noir',
    name: 'Noir',
    tagline: 'Lounge & nightlife — dark with gold accents',
    themes: noir,
  },
  {
    key: 'gallery',
    name: 'Gallery',
    tagline: 'Fast casual — photo-forward cards',
    themes: gallery,
  },
  {
    key: 'bistro',
    name: 'Bistro',
    tagline: 'Neighbourhood eatery — warm, hand-drawn feel',
    themes: bistro,
  },
  {
    key: 'grand',
    name: 'Grand',
    tagline: 'Hotel & banquet — formal two-column',
    themes: grand,
  },
];

export function getArchetype(templateKey: string): ArchetypeMeta {
  return ARCHETYPES.find((a) => a.key === templateKey) || ARCHETYPES[1]; // minimal
}

export function resolveTheme(templateKey: string, themeKey: string): MenuTheme {
  const archetype = getArchetype(templateKey);
  return (
    archetype.themes.find((t) => t.key === themeKey) || archetype.themes[0]
  );
}
